import type { CaseIntelligenceSnapshot } from './types';

function toDateString(date: Date) {
  return date.toISOString().slice(0, 10);
}

function addDays(days: number) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + days);
  return date;
}

const now = new Date().toISOString();
const hearingDate = addDays(14);
const filingDueDate = addDays(1);

export function createFallbackCaseIntelligence(userId = ''): CaseIntelligenceSnapshot {
  return {
    cases: [
    {
      id: 'fallback-case',
      user_id: userId,
      title: 'In re: Marriage of Chen',
      case_number: 'FL-24-0918',
      court_name: 'Superior Court of California',
      department: 'Dept. 24',
      judge_name: null,
      case_type: 'custody_modification',
      status: 'active',
      county: 'Alameda',
      state: 'CA',
      is_active: true,
      next_hearing_at: hearingDate.toISOString(),
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    children: [
    {
      id: 'fallback-child',
      user_id: userId,
      case_id: 'fallback-case',
      name: 'Leonie Chen',
      date_of_birth: null,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    people: [
    {
      id: 'fallback-person-primary',
      user_id: userId,
      case_id: 'fallback-case',
      display_name: 'Sarah Chen',
      role: 'petitioner',
      relationship: 'parent',
      email: null,
      phone: null,
      is_primary_client: true,
      notes: null,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    entries: [
    {
      id: 'fallback-entry-exchange',
      user_id: userId,
      case_id: 'fallback-case',
      child_id: 'fallback-child',
      entry_type: 'pickup_dropoff',
      event_date: toDateString(addDays(-1)),
      event_time: '18:10:00',
      event_end_time: null,
      custody_period: 'transition',
      title: 'Drop-off completed',
      body: 'Brief exchange at the regular location.',
      child_mood: 'quiet',
      is_flagged: false,
      flag_severity: null,
      flag_category: null,
      issue_key: 'exchanges',
      location_name: null,
      location_lat: null,
      location_lng: null,
      metadata: {},
      voice_transcript: null,
      capture_method: 'fallback',
      content_hash: null,
      is_edited: false,
      private_notes: null,
      court_ready_summary: null,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      id: 'fallback-entry-denied',
      user_id: userId,
      case_id: 'fallback-case',
      child_id: 'fallback-child',
      entry_type: 'visit_denied',
      event_date: toDateString(addDays(-7)),
      event_time: '09:00:00',
      event_end_time: null,
      custody_period: 'my_time',
      title: 'Scheduled exchange did not happen',
      body: 'The exchange did not occur at the scheduled time.',
      child_mood: null,
      is_flagged: true,
      flag_severity: 'medium',
      flag_category: 'denied_visit',
      issue_key: 'missed_exchanges',
      location_name: null,
      location_lat: null,
      location_lng: null,
      metadata: {},
      voice_transcript: null,
      capture_method: 'fallback',
      content_hash: null,
      is_edited: false,
      private_notes: null,
      court_ready_summary: null,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    evidenceAttachments: [],
    courtOrders: [],
    courtOrderProvisions: [],
    filingPackages: [
    {
      id: 'fallback-filing-fl150',
      user_id: userId,
      case_id: 'fallback-case',
      title: 'Serve your FL-150',
      filing_type: 'fl_150',
      status: 'draft',
      due_date: toDateString(filingDueDate),
      completion_percent: 72,
      court_ready_summary: 'Income and Expense declaration drafted from saved financial records.',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    keyDates: [
    {
      id: 'fallback-hearing',
      user_id: userId,
      case_id: 'fallback-case',
      date_type: 'hearing',
      event_date: toDateString(hearingDate),
      event_time: '09:00:00',
      title: 'RFO hearing',
      description: 'Custody modification hearing.',
      is_completed: false,
      related_filing_package_id: 'fallback-filing-fl150',
      related_court_order_id: null,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    patternTags: [
    {
      id: 'fallback-pattern',
      user_id: userId,
      case_id: 'fallback-case',
      issue_key: 'missed_exchanges',
      label: 'Missed exchanges',
      severity: 'medium',
      description: 'A small set of exchange issues is present in the log.',
      source_entry_ids: ['fallback-entry-denied'],
      first_seen_on: toDateString(addDays(-7)),
      last_seen_on: toDateString(addDays(-7)),
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    ],
    aiOutputs: [],
    advisorThreads: [],
  };
}
